src/app/error.tsx

Test: first commit

---

src/app/feed/page.tsx

채정님과 작업하기 위한 피드 페이지 폴더 생성하고 분리 했습니다.
`나래 -> 칼럼`
`채정 -> 퀴즈`
- app 내 feed 디렉터리 생성
- feed 디렉터리 내, column과 quiz 분리

Add Feed Folder

---

src/app/feed/column/page.tsx
src/app/feed/quiz/page.tsx

Divide Feed Page

---

src/utils/jsToNative.ts

close #26 
- Add jsToNative util

Feat: Add jsToNative util

---

src/states/server/Post/getTopicList.ts

fetch ssr 이슈
- fetch를 client -> server로 바꾸었습니다.

Feature/ssr: fetch ssr 이슈

---

src/app/api/GET/route.ts

Fix: Set Token

---

.github/workflows/deploy.yml

- CI(github action) slack messsage

Chore: Add ci slack msg

---

package.json
src/firebase.ts
yarn.lock

close #35
- Firebase 설치
- GA 기본 설정

Feat: Add firebase utils

---

src/firebase.ts

Fix: Update firebase env key name

---

src/states/server/Home/getCategory.ts

test: build

---

next.config.js
src/api/request_csr.ts
src/api/request_ssr.ts
src/app/api/GET/route.ts
src/utils/url.ts

test: build2

---

src/api/request_csr.ts
src/api/request_ssr.ts

fix: api route domain

---

next.config.js
src/app/_component/Catergory/CategoryCard.tsx

0506: main api bug test

---

.github/workflows/pr_approve.yml
.github/workflows/pr_review.yml

Add pr review slack bots
- pr review bot
- pr approve bot

chore: Add pr review slack bots

---

src/app/menu/page.tsx

현재 버전을 native에서 가져온다
clsoe #51 
- 현재버전 jsToNative

feat: add currentVersion from native

---

src/app/_component/Nav/PostNav.tsx
src/app/_component/Post/PostScreen.tsx

native share 기능 추가
close #50 
- 공유하기 추가

feat: add share jstonative

---

src/app/home/_component/ListContent.module.css
src/app/menu/announcement/_component/AnnouncementList.module.css
src/app/menu/announcement/_component/AnnouncementList.tsx
src/app/menu/announcement/announcemnet.module.css
src/app/menu/announcement/page.tsx
src/app/menu/page.tsx
src/app/search/_component/TopSearch.tsx
src/hooks/useIntersectionObserver.ts
src/model/Announce.ts
src/states/server/Menu/getAnnounce.ts
src/states/server/queries.ts
src/utils/formatter.ts

feat: 공지사항 ui & api 연동 구현

---

src/app/[category]/[topicId]/page.tsx
src/app/_component/Catergory/TopicList.tsx
src/app/_component/Nav/PostNav.tsx
src/app/_component/Post/PostScreen.module.css
src/app/_component/Post/PostScreen.tsx
src/app/menu/scrap/_component/ScrapContent.tsx
src/model/NextTopic.ts
src/states/server/Home/getNextTopic.ts
src/states/server/queries.ts

- scrap 추가
- img 연동
- nextTopic api 추가
- 작업1

fix: Post 페이지 api 추가 연동

---

src/components/Container/Container.module.css

fix: AppContainer Component Style

---

src/app/_component/Post/PostScreen.module.css

- UI) 토픽 상세 요약 부분 line-height 이슈 lineHeight 수정
- 작업1

FIN-43: UI) 토픽 상세 요약 부분 line-height

---

src/app/_component/Catergory/LoginModalContent.module.css

- UI) 로그인 하기 바텀 시트 버튼 색상 변경: Primary color로 수정

fin-46: UI) 로그인 하기 바텀 시트 버튼 색상 변경

---

next.config.js
package.json
sentry.client.config.ts
sentry.edge.config.ts
sentry.server.config.ts
src/app/global-error.tsx
src/instrumentation.ts
yarn.lock

- sentry configure
- 환경변수 NEXT_PUBLIC_SENTRY_DSN, SENTRY_AUTH_TOKEN 추가
- sentry configure

chore: add sentry configure

---

src/utils/jsToNative.ts

CustomEvent Bus와 Unique callback id 생성
- CustomEvent Bus
```ts
// Custom Event의 안정성 확보 
type EventHandler = (payload: any) => void;
class FHEventBus {
on(key: string, handler: EventHandler): () => void {
const eventListener = (e: CustomEvent) => handler(e.detail);
window.addEventListener(key, eventListener as EventListener);
return () => this.off(key, eventListener as EventListener);
}
off(key: string, handler: EventHandler): void {
window.removeEventListener(key, handler as EventListener);
}
emit(key: string, ...payload: Parameters<EventHandler>): void {
window.dispatchEvent(new CustomEvent(key, { detail: payload[0] }));
}
once(key: string, handler: EventHandler): void {
const handleOnce = (payload: any) => {
handler(payload);
this.off(key, handleOnce as EventHandler);
};
this.on(key, …
```

feat: add custom event bus & unique callbackid

---

src/api/client.ts

fix: client api refeshAccessToken

---

src/app/menu/_component/MenuScreen.tsx
src/utils/jsToNative.ts

https://fin-hub.atlassian.net/browse/FIN-4
- isAndroid, isIos 공통 모듈 개발
- jsToNative "getRemoteConfig" 추가

native 최신 버전 관리

---

public/icons/menu_comment1_icon.svg
public/icons/menu_comment_icon.svg
src/app/_component/Menu/LoginBox.tsx
src/app/_component/Post/UserTypeContent.tsx
src/app/menu/comment/_component/CommentCard.tsx
src/app/menu/comment/_component/ScrapComment.tsx
src/app/menu/comment/page.tsx
src/components/Toast/Toast.style.ts
src/components/Toast/ToastTemplates.tsx
src/model/MyComment.ts
src/states/server/Menu/getMyComment.ts
src/states/server/queries.ts

- 이슈 작업
- FIN-50: UI) 토스트 크기
- FIN-51: UI) 내 댓글 모아보기
- FIN-52: UI) 단어 요청 토스트 스타일
- FIN-54: UI) '을','를' 표기

FIN-50,51,52,54

---

src/app/search/_component/SearchScreen.tsx

- [x ] 🐞 버그 발생
- fin-40: UI) 검색어 입력값 없을 때 X버튼 제거

fin-40: UI) 검색어 입력값 없을 때 X버튼 제거

---

src/app/home/_component/ListContent.module.css

fin-45:UI)목록페이지 카테고리

---

src/app/menu/_component/MenuScreen.tsx
src/app/privacy/page.tsx

개인정보처리방침 페이지 생성
- 개인정보처리방침 페이지 생성

feat: add privacy page

---

src/app/menu/_component/MenuScreen.tsx
src/app/termsOfUse/page.tsx

이용약관 페이지 생성

---

src/app/_component/SafeArea.tsx
src/hooks/useSafeAreaTop.ts

Android에서 막는 부분 추가
- Android에서 Safearea jsToNative 코드 미호출
- Safearea 컴포넌트 작성
추가적으로 개선방향에 대한 commit을 올려보았는데요.
AppContainer단에서 `disabledTopArea`를 제어하고 계셔서 이 부분 코드를 첨부해봅니다(아래 코드는 commit하지 않은 제가 임의로 작성한 코드입니다)
1.이 부분에서 기존의 각 컴포넌트마다 customHook을 선언하는 방식이 아닌 컴포넌트로 Safearea 함께 처리할 수 있지 않을까 제안해봅니다:) 
2. 여기서 customHook을 선언하고 disabledTopArea에 따라 처리하는 방법도 있을 것 같아요!
```ts
export const AppContainer = ({ 
footer=true,
header=true,
disabledTopArea=false,
style = {},
children,
...props
}: AppContainerProps) => {
const top = useSafeAreaTop();
return (
<Box
className={cx([cssStyle.appContainerWrap, cssStyle.footer, header && cssStyle.header])}
style={{
position: 'relative',
marginTop: disabledTopArea ? 0 : top,
...style
}}
{...props}
>
<Safearea backgroundColor={safeareaBackgroundColor}>
{children} …
```

Safearea 개선

---

src/app/_component/Nav/MainNav.tsx
src/app/_component/Nav/PostNav.tsx
src/app/search/_component/SearchScreen.tsx
src/components/AppBar/AppBar.tsx

- commit 7609fd3 참조
- SafeArea Component 전체 적용
- 작업1

FIN-72: FE) Android 노치영역 오류 (SafeArea Component 적용)

---

src/app/_component/Catergory/TopicList.module.css
src/app/_component/Catergory/TopicList.tsx
src/app/_component/Post/PostScreen.tsx
src/model/Topic.ts

- [] 🐞 버그 발생
- 홈 > 토픽 리스트 이미지 추가

fix: home > topicList image 추가

---

src/api/auth.ts
src/app/_component/GlobalProvider.tsx
src/hooks/useAutoLogin.ts

- 자동 로그인 api 개선
- #101
- autoLogin hook 생성

refactor: auto login

---

src/api/client.ts
src/api/type.ts
src/app/menu/alarm/_component/PushItem.tsx
src/states/server/Menu/patchPushAlarmYn.ts
src/states/server/mutations.ts

- 메뉴 알림 페이지 푸심 알람 설정 api 연동
- OS 알림 설정 여부 검사
- 메뉴 알림 페이지 푸심 알람 설정 api 연동
- OS 알림 설정 여부 검사

fix: 메뉴 > 알림 설정페이지 api 연동

---

.github/workflows/deploy-dev.yml

github action CICD
- github action CICD script 작성 및 테스트

github action CICD

---

src/api/fcm.ts
src/app/menu/_component/LogOutButton.tsx

- 로그아웃 시 fcm db 삭제 요청
- 로그아웃 시 fcm db 삭제 요청

fix: logout remove fcm

---

src/app/menu/_component/MenuScreen.tsx

- 메뉴 페이지 하단 패딩 추가
- 메뉴 페이지 하단 패딩 추가

fix: Add menu screen padding bottom

---

src/app/feed/column/[columnId]/_component/ColumnDetailScreen.tsx
src/model/GptColumn.ts

UI) FIN-60 : 칼럼 상단 해시태그 버튼 클릭 시 해당 토픽 이동
- 해시태그 버튼 클릭 시 해당 토픽 이동

UI) FIN-60 : 칼럼 상단 해시태그 버튼 클릭 시 해당 토픽 이동

---

src/app/_component/RQProvider.tsx

loca에서 플로팅되어있으니 사용할 때 open하는 방향이 사용성에 더 좋다는 피드백 반영건입니다.
```ts
<ReactQueryDevtools initialIsOpen={false}/>
```
- AS-IS `process.env.NEXT_PUBLIC_MODE === 'local'`
- TO-BE `false`

chore: set in-active rq dev tools

---

src/app/feed/column/_component/ColumnCard.tsx
src/app/feed/column/_component/ColumnCardImg.tsx
src/app/feed/column/list/_component/ListCard.tsx
src/states/server/queries.ts

- Gpt 컬럼 swiper 속도 && 무한 스크롤 && 배경 이미지 수정
- Gpt 컬럼 swiper 속도 && 무한 스크롤 && 배경 이미지 수정

fix: Gpt 컬럼 swiper 속도 && 무한 스크롤

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml

CICD script 작성
- CICD script 작성(dev, prod)

Configure CICD 

---

src/app/feed/quiz/_component/styles.ts

UI) FIN-57 : 퀴즈- 캘린더 년도 클릭 시 해당 월만 보이는 오류 
- 월 글자색 블랙으로 변경
- 다른 월 클릭 가능하게 변경

UI) FIN-57 : 퀴즈- 캘린더 년도 클릭 시 해당 월만 보이는 오류 

---

src/components/Toast/ToastTemplates.tsx

- [ X] 🔨 리팩토링
UI)FIN-52 : 단어요청 토스트 스타일 
- 작업1

UI)FIN-52 검색 단어요청 토스트에 아이콘 추가

---

src/app/_component/Menu/MenuCard.tsx
src/app/menu/_component/MenuScreen.tsx

- 개인정보처리방침, 이용약관 링크 연결
- 개인정보처리방침, 이용약관 링크 연결
- 디자인 수정 예정

fix: 개인정보처리방침, 이용약관 링크 연결

---

src/api/auth.ts
src/app/api/auth/apple/route.ts
src/app/auth/apple/callback/page.tsx
src/app/login/page.tsx
src/configs/index.ts

feat: feat: add apple login

---

src/configs/index.ts

remove apple url reponse_mode
fin-78
- remove apple url reponse_mode

chore: update apple auth url reponse_mode

---

src/configs/index.ts

remove scope in apple auth url
fin-78
- remove scope in apple auth url

chore: remove scope in apple auth url

---

src/configs/index.ts

0824 비정기 반영

---

src/app/feed/quiz/_component/TodayQuiz.tsx

- FIN-106
- 비 로그인 유저 퀴즈 클릭 시 로그인 슬라이드 띄우기

FIN-106: 비로그인 시 퀴즈 풀기 시도 시 "잠시후 다시 시도해주세요"  토스트팝업

---

src/app/menu/_component/MenuScreen.tsx

- FIN-108
- FIN-108
- 메뉴 버튼 상단 알림 이동 추가

FIN-108: FE) 메뉴 버튼 상단 알림 이동 오류

---

src/app/feed/quiz/_component/TodayQuiz.tsx
src/app/feed/quiz/_component/TodayQuizPopup.tsx

- FIN-109
- FIN-109
- 오늘의 퀴즈, 팝업 font style 수정

FIN-109: 오늘의 퀴즈 글씨체 수정 요청

---

src/app/feed/quiz/_component/QuizItem.tsx
src/app/feed/quiz/_component/QuizList.tsx
src/app/feed/quiz/_component/QuizResult.tsx
src/app/feed/quiz/_hooks/useQuizListData.ts
src/app/feed/quiz/detail/_component/QuizDetailScreen.tsx
src/components/Tabs/Tabs.tsx
src/components/Text/Text.tsx
src/components/Text/Text.type.ts
src/components/Text/textUtils.ts

- quiz ui, api request 값 수정
- quiz ui 수정
- text component lineClamp prop 추가
- 기존 풀었던 퀴즈 에서는 정답인 값만 서버에서 주었는데, 모든 풀었던 퀴즈를 받을 수 있게 변경된 api spec 적용

fix: quiz ui, api request 값 수정

---

src/app/_component/AppLayout/AppLayout.tsx
src/app/_component/MenuBar/MenuBar.tsx
src/app/feed/column/[columnId]/_component/OpinionBox.tsx
src/app/feed/page.tsx
src/app/home/page.tsx
src/app/layout.tsx
src/app/list/page.tsx
src/app/menu/_component/MenuScreen.tsx
src/app/search/_component/SearchScreen.tsx
src/components/Container/AppContainer.tsx

- FIN-107
- FIN-107
- 첫 화면만 GNB 활성화

FIN-107: FE) 토픽 상세 하단 네비게이션 활성화 오류 (토픽 하위 경로 추가 필요)

---

src/app/feed/quiz/_component/styles.ts

UI)FIN-113:퀴즈 달력 > 요일 글자 크기 작음
- 작업1

UI)FIN-113:퀴즈 달력 > 요일 글자 크기 작음

---

next.config.js

- S3 에서 CDN 으로 요청 주소 변경으로 인한 next.config.js 외부 이미지 도메인 (CDN) 으로 변경
- - next.config.js 외부 이미지 도메인 (CDN) 으로 변경

fix: config image cdn 도메인

---

src/app/feed/column/[columnId]/_component/ColumnDetailScreen.tsx
src/styles/public.css

- backoffice tiptap editor 도입으로 인한 css file 공유 설정 및 main 적용
- import tiptap css file (cdn)
- add element with editor className (tiptap)

fix: tiptap editor style 적용 (import cdn css file)

---

src/api/client.ts
src/app/feed/column/[columnId]/comment/report/_component/ReportCommentScreen.tsx

- FIN-130
- FIN-130
- APIError 객체 server errorMsg 추가
- 신고하기 mutation onError 수정

FIN-130: 칼럼 댓글 신고 후 다시 신고 막음 처리 필요

---

.eslintrc.json

- off unused && delete storybook

chore: off unused && delete storybook

---

src/api/client.ts
src/app/_component/MSWComponent.tsx
src/app/loading.tsx

eslint rules을 바꾸면서 build 이슈 해결
- code fix

fix: fix eslint rules

---

src/api/client.ts
src/app/menu/user/_component/UserPageScreen.tsx
src/app/menu/user/email/_component/EmailSuggestionList.tsx
src/app/menu/user/email/_component/UpdateEmail.module.css
src/app/menu/user/email/_component/UpdateEmail.tsx
src/app/menu/user/email/page.tsx
src/states/server/Menu/patchEmail.ts
src/states/server/mutations.ts

Oauth 이메일 변경 화면 개발
https://fin-hub.atlassian.net/browse/FIN-140
- jsonParsing content-type 체크하도록 client 변경
- 이메일 변경 화면 개발

Oauth 이메일 변경 관련 이메일 사용 화면 로직 변경

---

src/components/Input/index.ts

fix: apply prettier

---

src/app/menu/termsPolicy/_component/TermsPolicyScreen.tsx
src/app/menu/voc/_component/VocScreen.tsx

FIN-77 이슈 추가 요청 사항 수정
https://fin-hub.atlassian.net/browse/FIN-77?atlOrigin=eyJpIjoiNDU4ZTcwOGY0NWJiNDRjMGExNDVjZDJjMTE5M2Y1MGEiLCJwIjoiaiJ9
- 외부 링크 이동시 띄운 팝업 기능 삭제

FIN-77: VOC 기능 #2

---

public/icons/check.svg
public/icons/icon_arrow_right_8.svg
src/api/auth.ts
src/app/auth/apple/callback/page.tsx
src/app/auth/google/callback/page.tsx
src/app/auth/kakao/callback/page.tsx
src/app/login/agree/_component/AgreeScreen.tsx
src/app/login/agree/_component/CheckIcon.tsx
src/app/login/agree/_component/CheckItem.tsx
src/app/login/agree/page.tsx
src/app/menu/termsPolicy/_component/TermsPolicyScreen.tsx
src/model/User.ts
src/states/client/atoms/user.ts
src/states/server/Login/postAgreement.ts
src/states/server/mutations.ts

FIN-102: 최초 회원가입 시 약관 2개 동의 받기
https://fin-hub.atlassian.net/browse/FIN-102?atlOrigin=eyJpIjoiZTgxMTIwZmI4OTJlNGMxMDgxZmNiMjhlODEwMjVmMzQiLCJwIjoiaiJ9
- 회원가입 약관 동의 화면 추가
- login return spec 수정 (add isMember)

FIN-102: 최초 회원가입 시 약관 2개 동의 받기

---

src/app/feed/column/[columnId]/_component/ColumnDetailScreen.tsx

FIN-111: GPT칼럼 안드로이드 공유하기 버튼 안눌림
https://fin-hub.atlassian.net/browse/FIN-111?atlOrigin=eyJpIjoiNTNiY2M2YWZhMjllNGU1MDgzZjQwMzdiZWU0ZmQ5MWMiLCJwIjoiaiJ9
- 공유하기 기능 연결

FIN-111: GPT칼럼 안드로이드 공유하기 버튼 안눌림

---

src/app/feed/column/[columnId]/_component/ColumnDetailScreen.tsx
src/app/feed/column/[columnId]/_component/OpinionBox.tsx
src/app/feed/column/[columnId]/comment/page.tsx

FIN-156: 칼럼 댓글 로그인 처리
https://fin-hub.atlassian.net/browse/FIN-156?atlOrigin=eyJpIjoiOGViMDU5Nzk4OGQ0NGRkYTlhMTE1ZjU1YWMwMWMzZjQiLCJwIjoiaiJ9
- 로그인 모달 띄우기

FIN-156: 칼럼 댓글 로그인 처리

---

src/app/feed/column/[columnId]/comment/post/_component/PostCommentScreen.tsx
src/app/home/page.tsx
src/app/search/_component/SearchScreen.tsx
src/app/search/hooks/useInput.ts

FIN-150: 댓글 입력하려고 할 시 키패드 및 커서 요청
https://fin-hub.atlassian.net/browse/FIN-150?atlOrigin=eyJpIjoiMDBkNzI3MTRjYTRkNDUxMThjMTQyOGMzZjc4OTE0MzIiLCJwIjoiaiJ9
- 홈에서 검색페이지로 들어왔을 때 만 input focus
- 컬럼 댓글 페이지 들어왔을 때 input focus

FIN-150: 댓글 입력하려고 할 시 키패드 및 커서 요청

---

.github/workflows/deploy-dev.yml
.github/workflows/deploy-prod.yml
.github/workflows/pr_approve.yml
.github/workflows/pr_lint.yml
.github/workflows/pr_merged.yml
.github/workflows/pr_review.yml
package.json

chore: add workflow-dispatch && lint job
- add workflow-dispatch
- add lint check job

chore: add workflow-dispatch && lint job

---

.github/workflows/pr_lint.yml

- yarn cache 사용
참고 자료
https://github.com/actions/cache/blob/main/examples.md#node---yarn
- yarn cache 사용

chore: lint workflow add yarn-cache

---

src/app/menu/alarm/_component/AlarmPageScreen.tsx
src/app/menu/alarm/_component/DisagreePopup.tsx
src/app/menu/alarm/_component/PushItem.tsx
src/app/menu/alarm/_component/PushMarketingOptIn.module.css
src/app/menu/alarm/_component/PushMarketingOptIn.tsx
src/app/menu/alarm/_component/PushMarketingOptInPageScreen.tsx
src/app/menu/alarm/_component/PushMarketingTableRow.tsx
src/app/menu/alarm/pushMarketingOptIn/page.tsx
src/components/Toast/BasicToast.tsx
src/components/Toast/ScrapToast.tsx
src/hooks/useScroll.ts
src/utils/formatter.ts

푸시 알림 로직, 디자인 수정
https://fin-hub.atlassian.net/browse/FIN-122
- 마케팅 동의
- 알람 설정

푸시 알림 로직, 디자인 수정

---

src/utils/formatter.ts

일자 method 수정
https://fin-hub.atlassian.net/browse/FIN-122
- 날짜 일자 method 수정

fix: change datetimeFomatter date method

---

src/app/menu/scrap/_component/ScrapContent.module.css
src/app/menu/scrap/_component/ScrapContent.tsx
src/model/MyScrap.ts

FIN-119: 메뉴 > 내 스크랩 이미지 안뜨는 현상
https://fin-hub.atlassian.net/browse/FIN-119?atlOrigin=eyJpIjoiODczZTVmN2JmMTk3NDM4MGEwOGY2Yzk1ODlmYWYyYTAiLCJwIjoiaiJ9
- API spec 변경 (imgUrl 추가)
- 스크랩 imgUrl 적용

FIN-119: 메뉴 > 내 스크랩 이미지

---

src/app/_component/Catergory/HomeContent.tsx
src/app/feed/column/[columnId]/_component/ColumnDetailScreen.tsx
src/app/feed/column/page.tsx
src/app/menu/scrap/_component/ScrapContent.tsx
src/app/menu/user/name/_component/UpdateNickName.tsx
src/app/search/_component/SearchScreen.tsx

FIN-149: 워딩 수정 요청

---

src/app/feed/column/list/page.tsx

FIN-149: 워딩 수정 요청 #2

---

src/app/menu/alarm/_component/AlarmPageScreen.tsx
src/app/menu/alarm/_component/PushMarketingOptInPageScreen.tsx

푸시알림 AlarmAgreeModal 추가
- 푸시알림 AlarmAgreeModal 추가

feat: add AlarmAgreeModal on alarm pages

---

src/app/menu/alarm/_component/AlarmPageScreen.tsx
src/app/menu/alarm/_component/PushMarketingOptInPageScreen.tsx

early return으로 인해 toast가 노출되지 않는 이슈가 있었습니다.
- early return 제거

fix: remove early return
